variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

cache:
  key: ${CI_BUILD_STAGE}
  paths:
    - .gradle

build for all:
  image: openjdk:8-jdk-alpine
  tags:
    - wallet-dev
  stage: build
  script:
    - pwd
    - ./gradlew wallet-webapi:bootRepackage
    - ./gradlew wallet-task:bootRepackage
    - ./gradlew wallet-hsm:bootRepackage
  artifacts:
    paths:
      - wallet-webapi/build/libs/*.jar
      - wallet-hsm/build/libs/*.jar
      - wallet-task/build/libs/*.jar
    expire_in: 20min

deploy for cl-webapi:
  image: gitlab/dind:latest
  tags:
    - wallet-dev
  stage: deploy
  script:
    - docker stop -f wallet-webapi ||true
    - docker rm -f wallet-webapi ||true
    - docker rmi wallet-webapi ||true
    - docker build -t wallet-webapi wallet-webapi/.
    - docker run -d --name wallet-webapi -p 10001:10001 -v /etc/localtime:/etc/localtime cl-webapi
  when: manual

deploy for cl-task:
  image: gitlab/dind:latest
  tags:
    - wallet-dev
  stage: deploy
  script:
    - docker stop -f wallet-task ||true
    - docker rm -f wallet-task ||true
    - docker rmi wallet-task ||true
    - docker build -t wallet-task wallet-task/.
    - docker run -d --name wallet-task -p 10033:10033 -v /etc/localtime:/etc/localtime wallet-task
  when: manual

deploy for cl-hsm:
  image: gitlab/dind:latest
  tags:
    - wallet-dev
  stage: deploy
  script:
    - docker stop -f wallet-hsm ||true
    - docker rm -f wallet-hsm ||true
    - docker rmi wallet-hsm ||true
    - docker build -t wallet-hsm wallet-hsm/.
    - docker run -d --name wallet-hsm -p 10888:10888 -v /etc/localtime:/etc/localtime -v /mnt/wallets:/mnt/wallets cl-hsm
  when: manual

after_script:
  - echo "End CI"