variables:
  DOCKER_DRIVER: overlay2
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - deploy

cache:
  key: ${CI_BUILD_STAGE}
  paths:
    - .gradle
    - build

build:
  image: eclipse-temurin:17-jdk-alpine
  tags:
    - wallet-dev
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew bootJar --no-daemon -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 hour

deploy wallet-app:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - wallet-dev
  stage: deploy
  script:
    - docker stop wallet-app || true
    - docker rm wallet-app || true
    - docker rmi wallet-app || true
    - docker build -t wallet-app -f Dockerfile .
    - docker run -d --name wallet-app --restart unless-stopped -p 8080:8080 -v /etc/localtime:/etc/localtime:ro -v /mnt/wallets:/data/keystores --env-file /etc/wallet/wallet.env wallet-app
  when: manual

after_script:
  - echo "End CI"
