concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "pie"
  url = "http://192.168.123.83:81/"
  token = "2b1x3XyS7tRKz2dgybWH"
  executor = "docker"
  clone_url = "http://192.168.123.83:81"
  [runners.custom_build_dir]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true  #1
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/root/.gradle:/root/.gradle","/var/run/docker.sock:/var/run/docker.sock","/cache"]  #2
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]